env_name: ALE/Breakout-v5
render_mode: rgb_array
resize: 84
num_stack: 4
num_skip: 4

model_type: DQN
learning_rate: 0.0001
buffer_size: 100000
learning_starts: 50000
batch_size: 32
gamma: 0.99
target_update_interval: 10000
train_freq: 4
exploration_fraction: 0.1
exploration_final_eps: 0.01

total_timesteps: 4000000
save_path: ./models/BreakPoint
use_cuda: true
run_label: DQN
seed: 42

