algo: "dqn"
policy: "CnnPolicy"
levels:
  - "SuperMarioBros-1-1-v0"
resize: 84
num_stack: 4
num_skip: 2
render_mode: None
action_set: "RIGHT_ONLY"

learning_rate: 0.0003
total_timesteps: 2000000  
seed: 67
